import { expect, test } from '@playwright/test';
import path from 'node:path';

/** Auth state files generated by global-setup (session already established). */
const TRANSPORTER_AUTH = path.join(__dirname, '.auth/transporter.json');
const ADMIN_AUTH = path.join(__dirname, '.auth/admin.json');
const TRANSPORTER_EMAIL = 'transport@demo.dz';
const TRANSPORTER_PASSWORD = 'transport123';
const ADMIN_EMAIL = 'admin@swiftcolis.dz';
const ADMIN_PASSWORD = 'admin123';

/** Navigate to the transporter dashboard and wait for the tablist (JIT already done by globalSetup). */
async function goToTransporterDashboard(page: any) {
  await page.goto('/fr/dashboard/transporter', { waitUntil: 'domcontentloaded' });
  if (page.url().includes('/auth/login')) {
    await page.getByRole('textbox', { name: /adresse email|email/i }).fill(TRANSPORTER_EMAIL);
    await page.getByRole('textbox', { name: /mot de passe/i }).fill(TRANSPORTER_PASSWORD);
    await page.getByRole('button', { name: /se connecter/i }).click();
    await page.waitForURL('**/fr/dashboard/transporter**', { timeout: 120_000 });
  }

  const autoAssignTab = page.getByRole('tab').filter({ hasText: /auto-assign/i }).first();
  const visible = await autoAssignTab.isVisible({ timeout: 10_000 }).catch(() => false);
  if (!visible) {
    await page.reload({ waitUntil: 'domcontentloaded' });
  }
  await autoAssignTab.waitFor({ state: 'visible', timeout: 120_000 });
}

test.describe('Auto-assign — Préférences transporteur', () => {
  // Reuse the pre-authenticated session generated in globalSetup.
  test.use({ storageState: TRANSPORTER_AUTH });

  test('transporteur peut ouvrir l\'onglet Auto-assign', async ({ page }) => {
    test.setTimeout(180_000);
    await goToTransporterDashboard(page);

    // Cliquer sur l'onglet Auto-assign
    await page.getByRole('tab').filter({ hasText: /auto-assign/i }).first().click();

    // Vérifier les sections principales
    // Wait for the async data fetch inside AutoAssignTab to complete (replaces default 5s assertion timeout).
    await expect(page.locator('[data-testid="auto-assign-activation-card"]')).toBeVisible({ timeout: 60_000 });
    await expect(page.locator('[data-testid="auto-assign-zones-card"]')).toBeVisible({ timeout: 10_000 });
    await expect(page.locator('[data-testid="auto-assign-criteria-card"]')).toBeVisible({ timeout: 10_000 });
  });

  test('peut activer et sauvegarder l\'auto-assign', async ({ page }) => {
    test.setTimeout(180_000);
    await goToTransporterDashboard(page);

    await page.getByRole('tab').filter({ hasText: /auto-assign/i }).first().click();

    // Wait for tab content to fully load before any interaction.
    await page.locator('[data-testid="auto-assign-activation-card"]').waitFor({ state: 'visible', timeout: 60_000 });

    // Toggle auto-assign (le bouton est purement CSS rounded-full dans AutoAssignTab).
    const toggle = page.locator('[data-testid="auto-assign-activation-card"] button[class*="rounded-full"]').first();
    await toggle.click();

    // Changer le schedule via le sélecteur data-testid.
    await page.locator('[data-testid="auto-assign-schedule-select"]').click();
    await page.getByRole('option', { name: /18h/i }).click();

    // Mettre à jour max missions
    await page.locator('input[type="number"]').first().fill('15');

    // Sauvegarder
    const saveResponsePromise = page.waitForResponse((response) =>
      response.url().includes('/api/transporters/preferences') && response.request().method() === 'POST'
    );
    await page.getByRole('button', { name: /enregistrer les préférences/i }).click();
    const saveResponse = await saveResponsePromise;

    // Validate successful persistence; toast visibility is flaky in CI/dev under heavy render load.
    expect(saveResponse.ok()).toBeTruthy();
  });

  test('peut ajouter et supprimer une ville préférée', async ({ page }) => {
    test.setTimeout(180_000);
    await goToTransporterDashboard(page);

    await page.getByRole('tab').filter({ hasText: /auto-assign/i }).first().click();

    // Ajouter une ville préférée
    await page.getByPlaceholder('Ex: Alger, Oran, Blida…').fill('Alger');
    await page.getByRole('button', { name: 'Ajouter' }).first().click();

    // Vérifier que le badge apparaît
    await expect(page.locator('span').filter({ hasText: /^Alger$/ }).first()).toBeVisible();

    // Supprimer la ville
    const badge = page.locator('span:has-text("Alger")').locator('..').locator('button');
    await badge.click();

    // Vérifier disparition
    await expect(page.locator('[class*="bg-emerald-100"]:has-text("Alger")')).not.toBeVisible();
  });

  test('affiche un warning si critères de scoring = 0', async ({ page }) => {
    test.setTimeout(180_000);
    await goToTransporterDashboard(page);

    await page.getByRole('tab').filter({ hasText: /auto-assign/i }).first().click();

    // Wait for AutoAssignTab to finish loading its data before touching sliders.
    await page.locator('[data-testid="auto-assign-criteria-card"]').waitFor({ state: 'visible', timeout: 30_000 });

    // Mettre tous les sliders à 0 avec le native setter React.
    const sliders = page.locator('input[type="range"]');
    const count = await sliders.count();
    for (let i = 0; i < count; i++) {
      await sliders.nth(i).evaluate((element) => {
        const input = element as HTMLInputElement;
        // Use the native property setter so React's controlled-input tracking reacts correctly.
        const nativeSet = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, 'value')!.set!;
        nativeSet.call(input, '0');
        input.dispatchEvent(new Event('input', { bubbles: true }));
        input.dispatchEvent(new Event('change', { bubbles: true }));
      });
    }

    // Vérifier warning via data-testid (évite la dépendance au texte exact).
    await expect(page.locator('[data-testid="scoring-zero-warning"]')).toBeVisible({ timeout: 5_000 });

    // Bouton sauvegarder désactivé
    await expect(page.getByRole('button', { name: /enregistrer les préférences/i })).toBeDisabled();
  });
});

test.describe('Auto-assign — API Préférences', () => {
  test('GET /api/transporters/preferences crée les préférences par défaut', async ({ request }) => {
    // Seed et login pour obtenir un token valide
    await request.get('/api/seed');

    const loginRes = await request.post('/api/auth/callback/credentials', {
      data: { email: TRANSPORTER_EMAIL, password: TRANSPORTER_PASSWORD },
    });

    // Test GET préférences
    const res = await request.get('/api/transporters/preferences');

    // Si 200, vérifier structure
    if (res.status() === 200) {
      const data = await res.json();
      expect(data).toHaveProperty('autoAssignEnabled');
      expect(data).toHaveProperty('maxDailyMissions');
      expect(data).toHaveProperty('maxActiveParallel');
      expect(data).toHaveProperty('scoreWeightDistance');
    }
  });

  test('GET /api/transporters/auto-assign retourne les compteurs', async ({ request }) => {
    await request.get('/api/seed');

    const res = await request.get('/api/transporters/auto-assign');

    if (res.status() === 200) {
      const data = await res.json();
      expect(data).toHaveProperty('enabled');
      expect(data).toHaveProperty('todayCount');
      expect(data).toHaveProperty('activeCount');
    }
  });

  test('GET /api/transporters/analytics retourne les métriques', async ({ request }) => {
    await request.get('/api/seed');

    const res = await request.get('/api/transporters/analytics');

    if (res.status() === 200) {
      const data = await res.json();
      expect(data).toHaveProperty('totalAssigned');
      expect(data).toHaveProperty('totalCompleted');
      expect(data).toHaveProperty('successRate');
      expect(data).toHaveProperty('topRoutes');
      expect(data).toHaveProperty('monthlyStats');
      expect(typeof data.successRate).toBe('number');
      expect(data.successRate).toBeGreaterThanOrEqual(0);
      expect(data.successRate).toBeLessThanOrEqual(100);
    }
  });
});

test.describe('Auto-assign — Cron endpoint', () => {
  test('GET /api/cron/auto-assign sans secret retourne 401 si CRON_SECRET défini', async ({ request }) => {
    const res = await request.get('/api/cron/auto-assign');

    // Si le secret est configuré, doit retourner 401
    // Si pas de secret configuré, doit retourner 200 (pas de secret requis)
    expect([200, 401]).toContain(res.status());
  });

  test('GET /api/cron/auto-assign avec schedule filter ne plante pas', async ({ request }) => {
    // Utiliser la clé de seed comme secret de test
    const res = await request.get('/api/cron/auto-assign?schedule=DAILY_8AM&secret=test-secret');

    // Peut retourner 200 (succès, 0 assignés) ou 401 (wrong secret)
    expect([200, 401]).toContain(res.status());

    if (res.status() === 200) {
      const data = await res.json();
      expect(data).toHaveProperty('success');
      expect(data).toHaveProperty('schedule');
      expect(data).toHaveProperty('totalAssigned');
      expect(data.schedule).toBe('DAILY_8AM');
    }
  });
});

test.describe('Auto-assign — Dashboard Admin', () => {
  test.use({ storageState: ADMIN_AUTH });

  test('admin peut déclencher matching pour tous les transporteurs', async ({ page }) => {
    test.setTimeout(180_000);

    // Session from storageState can occasionally expire during long suites: fallback to UI login when redirected.
    await page.goto('/fr/dashboard/admin', { waitUntil: 'domcontentloaded' });
    if (page.url().includes('/auth/login')) {
      await page.getByRole('textbox', { name: /adresse email|email/i }).fill(ADMIN_EMAIL);
      await page.getByRole('textbox', { name: /mot de passe/i }).fill(ADMIN_PASSWORD);
      await page.getByRole('button', { name: /se connecter/i }).click();
      await page.waitForURL('**/fr/dashboard/admin', { timeout: 120_000 });
    }

    await expect(page.getByRole('heading', { name: /Administration SwiftColis/i })).toBeVisible({ timeout: 120_000 });
    await expect(page.getByText(/Matching transporteur automatique/i)).toBeVisible({ timeout: 60_000 });
  });
});

test.describe('Auto-assign — Limites et validations', () => {
  test('transporteur à capacité pleine ne reçoit pas de nouvelles missions', async ({ request }) => {
    await request.get('/api/seed');

    // Tester le statut auto-assign
    const statusRes = await request.get('/api/transporters/auto-assign');

    if (statusRes.status() === 200) {
      const status = await statusRes.json();
      // Si capacité pleine, canAssignMore doit être false
      if (status.activeCount >= status.maxActiveParallel || status.todayCount >= status.maxDailyMissions) {
        expect(status.canAssignMore).toBe(false);
      }
    }
  });

  test('PUT /api/transporters/auto-assign déclenche et retourne résumé', async ({ request }) => {
    await request.get('/api/seed');

    const res = await request.put('/api/transporters/auto-assign', {
      data: { limit: 5 },
    });

    // Peut retourner 200 (OK), 401 (session expirée/non authentifiée), 403 (auto-assign désactivé), ou 409 (capacité pleine)
    expect([200, 401, 403, 409]).toContain(res.status());

    if (res.status() === 200) {
      const data = await res.json();
      expect(data).toHaveProperty('summary');
      expect(typeof data.summary.success).toBe('number');
      expect(typeof data.summary.total).toBe('number');
    }

    if (res.status() === 403) {
      const data = await res.json();
      expect(data.error).toContain('non activé');
    }
  });
});
