ALTER TABLE "Relais"
ADD COLUMN IF NOT EXISTS "operationalStatus" TEXT NOT NULL DEFAULT 'ACTIF';

ALTER TABLE "Relais"
ADD COLUMN IF NOT EXISTS "suspensionReason" TEXT;

ALTER TABLE "Relais"
ADD COLUMN IF NOT EXISTS "suspendedAt" TIMESTAMP(3);
