-- prod-wipe-and-restore-local-users.sql
-- 1) TRUNCATE all user-related data (CASCADE handles FK chains)
-- 2) INSERT 5 real local users + relais + applications

TRUNCATE TABLE "User" CASCADE;

-- Auto-generated by scripts/generate-prod-insert-sql.cjs
-- Generated at 2026-04-12T12:22:51.232Z
-- Users to insert/update: admin@swiftcolis.dz, shopteek@gmail.com, bmwxdrive44@gmail.com, soniatrans44@gmail.com, bmwxdrive4x44@gmail.com

INSERT INTO "User" (id, email, password, name, "firstName", "lastName", address, role, phone, siret, image, "isActive", "clientType", "eligibleProImplicit", "eligibleProSince", "proLastEvaluatedAt", "weeklyValidShipments", "createdAt", "updatedAt")
VALUES (
  'cmng687520006u2l0xhpv9hcc', 'admin@swiftcolis.dz', '$2b$12$xf6gDZwg3IwV0zUMf9q0G.ra1NdmOylXWCKDlY9p0Kxw5mD3v3Rhu', 'Admin SwiftColis',
  NULL, NULL, NULL, 'ADMIN',
  '+213555000000', NULL, NULL, TRUE,
  'STANDARD', FALSE, NULL,
  NULL, 0, '2026-04-01T14:58:42.854Z', '2026-04-12T10:04:43.202Z'
)
ON CONFLICT (email) DO UPDATE SET
  name = EXCLUDED.name,
  password = EXCLUDED.password,
  "firstName" = EXCLUDED."firstName",
  "lastName" = EXCLUDED."lastName",
  address = EXCLUDED.address,
  role = EXCLUDED.role,
  phone = EXCLUDED.phone,
  "isActive" = EXCLUDED."isActive",
  "clientType" = EXCLUDED."clientType",
  "updatedAt" = EXCLUDED."updatedAt";

INSERT INTO "User" (id, email, password, name, "firstName", "lastName", address, role, phone, siret, image, "isActive", "clientType", "eligibleProImplicit", "eligibleProSince", "proLastEvaluatedAt", "weeklyValidShipments", "createdAt", "updatedAt")
VALUES (
  'cmnu90zjg0008u2yodvndzn08', 'shopteek@gmail.com', '$2b$12$HxHAzLHW5DTZ3ECsJkXCROKlKeneiX8rAl3G93DO70/ETDE02HVJW', 'Mohammed Bentebib',
  'Mohammed', 'Bentebib', '21 avenue de gambetta', 'CLIENT',
  '0656898789', NULL, NULL, TRUE,
  'STANDARD', FALSE, NULL,
  '2026-04-11T11:50:44.738Z', 0, '2026-04-11T11:25:51.724Z', '2026-04-11T11:50:44.742Z'
)
ON CONFLICT (email) DO UPDATE SET
  name = EXCLUDED.name,
  password = EXCLUDED.password,
  "firstName" = EXCLUDED."firstName",
  "lastName" = EXCLUDED."lastName",
  address = EXCLUDED.address,
  role = EXCLUDED.role,
  phone = EXCLUDED.phone,
  "isActive" = EXCLUDED."isActive",
  "clientType" = EXCLUDED."clientType",
  "updatedAt" = EXCLUDED."updatedAt";

INSERT INTO "User" (id, email, password, name, "firstName", "lastName", address, role, phone, siret, image, "isActive", "clientType", "eligibleProImplicit", "eligibleProSince", "proLastEvaluatedAt", "weeklyValidShipments", "createdAt", "updatedAt")
VALUES (
  'cmnuhbyan0000u2aoesu91mxa', 'bmwxdrive44@gmail.com', '$2b$12$8GRJK9ZkCkKc.PX7hf6jkOIlgfnNAK7JOwcH3AkL75D.3mGC36x4u', 'Sarah Ennaji',
  'Sarah', 'Ennaji', NULL, 'RELAIS',
  '0632659878', '16/0012345B22', NULL, TRUE,
  'STANDARD', FALSE, NULL,
  NULL, 0, '2026-04-11T15:18:20.255Z', '2026-04-11T17:08:40.392Z'
)
ON CONFLICT (email) DO UPDATE SET
  name = EXCLUDED.name,
  password = EXCLUDED.password,
  "firstName" = EXCLUDED."firstName",
  "lastName" = EXCLUDED."lastName",
  address = EXCLUDED.address,
  role = EXCLUDED.role,
  phone = EXCLUDED.phone,
  "isActive" = EXCLUDED."isActive",
  "clientType" = EXCLUDED."clientType",
  "updatedAt" = EXCLUDED."updatedAt";

INSERT INTO "User" (id, email, password, name, "firstName", "lastName", address, role, phone, siret, image, "isActive", "clientType", "eligibleProImplicit", "eligibleProSince", "proLastEvaluatedAt", "weeklyValidShipments", "createdAt", "updatedAt")
VALUES (
  'cmnukfzp60000u2dso0jxubpx', 'soniatrans44@gmail.com', '$2b$12$U9rK9pVboFxgCDQKXVA6deNBUk6i6Cg20r/wPtlokraIqTYFVcli2', 'Ilhem Ayoub',
  'Ilhem', 'Ayoub', NULL, 'RELAIS',
  '698987898', '16/0012345B21', NULL, TRUE,
  'STANDARD', FALSE, NULL,
  NULL, 0, '2026-04-11T16:45:27.526Z', '2026-04-11T17:03:26.921Z'
)
ON CONFLICT (email) DO UPDATE SET
  name = EXCLUDED.name,
  password = EXCLUDED.password,
  "firstName" = EXCLUDED."firstName",
  "lastName" = EXCLUDED."lastName",
  address = EXCLUDED.address,
  role = EXCLUDED.role,
  phone = EXCLUDED.phone,
  "isActive" = EXCLUDED."isActive",
  "clientType" = EXCLUDED."clientType",
  "updatedAt" = EXCLUDED."updatedAt";

INSERT INTO "User" (id, email, password, name, "firstName", "lastName", address, role, phone, siret, image, "isActive", "clientType", "eligibleProImplicit", "eligibleProSince", "proLastEvaluatedAt", "weeklyValidShipments", "createdAt", "updatedAt")
VALUES (
  'cmnuxhu260002u2bwq9hwnceo', 'bmwxdrive4x44@gmail.com', '$2b$12$xQikRgTBQozu7LDax5NXF.6eEeNoYoBuM6avO2/JlIwk9sxD3mNE.', 'ayoub belkacemi',
  'ayoub', 'belkacemi', NULL, 'TRANSPORTER',
  '0665988778', '16/0012345B29', NULL, TRUE,
  'STANDARD', FALSE, NULL,
  NULL, 0, '2026-04-11T22:50:48.558Z', '2026-04-11T22:56:24.687Z'
)
ON CONFLICT (email) DO UPDATE SET
  name = EXCLUDED.name,
  password = EXCLUDED.password,
  "firstName" = EXCLUDED."firstName",
  "lastName" = EXCLUDED."lastName",
  address = EXCLUDED.address,
  role = EXCLUDED.role,
  phone = EXCLUDED.phone,
  "isActive" = EXCLUDED."isActive",
  "clientType" = EXCLUDED."clientType",
  "updatedAt" = EXCLUDED."updatedAt";

INSERT INTO "Relais" (id, "userId", "commerceName", address, ville, "openTime", "closeTime", latitude, longitude, photos, "commerceDocuments", "commissionPetit", "commissionMoyen", "commissionGros", status, "operationalStatus", "suspensionReason", "suspendedAt", "cashCollected", "cashReversed", "cautionAmount", "cautionStatus", "cautionPaidAt", "activationDate", "firstActivityDate", "complianceScore", "createdAt", "updatedAt")
VALUES (
  'cmnujf0i30007u2aovqfbvc1a', 'cmnuhbyan0000u2aoesu91mxa', 'boulangerie', 'Boulevard Bouchekoum Amar, Cité Morsi (1074 lgts), Safsafa, Gué de Constantine, Daïra Bir Mourad Rais, Alger, 16064, Algérie', 'alger',
  NULL, NULL, NULL, NULL,
  NULL, '[{"url":"/uploads/commerce-docs/cmnuhbyan0000u2aoesu91mxa-1775924530318-jcelxf.png","filename":"Capture d''écran 2025-05-01 101904.png","size":242641}]',
  100, 200, 300,
  'PENDING', 'ACTIF', NULL, NULL,
  0, 0, NULL,
  'PENDING', NULL, NULL,
  NULL, 100, '2026-04-11T16:16:42.315Z', '2026-04-11T16:22:23.133Z'
)
ON CONFLICT (id) DO UPDATE SET
  "commerceName" = EXCLUDED."commerceName",
  address = EXCLUDED.address,
  ville = EXCLUDED.ville,
  "openTime" = EXCLUDED."openTime",
  "closeTime" = EXCLUDED."closeTime",
  status = EXCLUDED.status,
  "operationalStatus" = EXCLUDED."operationalStatus",
  "updatedAt" = EXCLUDED."updatedAt";

INSERT INTO "Relais" (id, "userId", "commerceName", address, ville, "openTime", "closeTime", latitude, longitude, photos, "commerceDocuments", "commissionPetit", "commissionMoyen", "commissionGros", status, "operationalStatus", "suspensionReason", "suspendedAt", "cashCollected", "cashReversed", "cautionAmount", "cautionStatus", "cautionPaidAt", "activationDate", "firstActivityDate", "complianceScore", "createdAt", "updatedAt")
VALUES (
  'cmnul34lr0003u2dsnlzoccpr', 'cmnukfzp60000u2dso0jxubpx', 'Peta Ha Commercial Center', 'M9G9+3HV, Oran, Algérie', 'oran',
  NULL, NULL, NULL, NULL,
  NULL, '[{"url":"/uploads/commerce-docs/cmnukfzp60000u2dso0jxubpx-1775926325574-oosbuf.png","filename":"Capture d''écran 2025-05-08 210641.png","size":46895}]',
  100, 200, 300,
  'PENDING', 'ACTIF', NULL, NULL,
  0, 0, NULL,
  'PENDING', NULL, NULL,
  NULL, 100, '2026-04-11T17:03:26.947Z', '2026-04-11T17:03:26.947Z'
)
ON CONFLICT (id) DO UPDATE SET
  "commerceName" = EXCLUDED."commerceName",
  address = EXCLUDED.address,
  ville = EXCLUDED.ville,
  "openTime" = EXCLUDED."openTime",
  "closeTime" = EXCLUDED."closeTime",
  status = EXCLUDED.status,
  "operationalStatus" = EXCLUDED."operationalStatus",
  "updatedAt" = EXCLUDED."updatedAt";

INSERT INTO "TransporterApplication" (id, "userId", "fullName", phone, vehicle, license, experience, regions, description, documents, status, "createdAt", "updatedAt")
VALUES (
  'cmnuxnqux0006u2bwcefo3u22', 'cmnuxhu260002u2bwq9hwnceo', 'ayoub belkacemi', '0665988778', 'Renault',
  'OR45896547', 10, '["alger","oran"]', 'gamberge',
  '[{"url":"/uploads/transporter-docs/cmnuxhu260002u2bwq9hwnceo-1775948120236-9zwldn.png","filename":"Capture d''écran 2025-05-01 143451.png","size":4202}]', 'APPROVED', '2026-04-11T22:55:24.345Z', '2026-04-11T22:56:24.645Z'
)
ON CONFLICT (id) DO UPDATE SET
  status = EXCLUDED.status,
  "updatedAt" = EXCLUDED."updatedAt";
